# Generated by Django 4.0.4 on 2022-05-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_remove_category_sub_cat_category_sub_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_cat',
            field=models.ManyToManyField(blank=True, to='store_app.subcategory'),
        ),
    ]
