# Generated by Django 4.0.4 on 2022-05-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0007_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='avaiability',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantita` di prodotti nel magazzino'),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_add_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data quando e` stato aggiunto per la prima volta'),
        ),
    ]
