# Generated by Django 4.0.4 on 2022-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_cart_user_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.JSONField(null=True),
        ),
    ]
